name: Trigger Imovirtual DAG

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - 'dags/imovirtual_dag.py'
      - 'dags/imovirtual/**'

jobs:
  trigger-airflow-dag:
    runs-on: ubuntu-latest
    
    env:
      AIRFLOW_HOME: ${GITHUB_WORKSPACE}/airflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Apache Airflow
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          mkdir -p ${AIRFLOW_HOME}/dags

      - name: Copy DAG files
        run: |
          cp -r dags/* ${AIRFLOW_HOME}/dags/
          
      - name: Initialize Airflow database
        run: |
          airflow db init
          airflow users create \
            --username admin \
            --firstname admin \
            --lastname admin \
            --role Admin \
            --email admin@example.com \
            --password admin
            
      - name: Trigger DAG
        run: |
          airflow dags unpause imovirtual_data_pipeline
          airflow dags trigger imovirtual_data_pipeline