name: Run Imovirtual Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering
  push:
    paths:
      - 'dags/imovirtual_dag.py'
      - 'dags/imovirtual/**'

jobs:
  run-imovirtual-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with dependencies

      - name: Run Imovirtual Data Pipeline
        run: |
          python dags/imovirtual_dag.py
